name: Feature branch Deploy

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'name branch to deploy'
        required: true
        type: string
    secrets:
      tf_api_token:
        description: 'trerraform access token'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TF_VAR_app_release:  ${{ needs.vars.outputs.app_release }}
      TF_VAR_tag:          ${{ needs.vars.outputs.app_release }}
      TF_VAR_app_branch:   ${{ needs.vars.outputs.app_branch }}
      TF_VAR_param_space:  ${{ needs.vars.outputs.param_space }}
      TF_WORKSPACE: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tf_api_token }}
          terraform_wrapper: false
          terraform_version: "~1.0"

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: iac

      - name: Cache Terraform
        uses: actions/cache@v2
        with:
          path: iac/.terraform
          key: ${{ hashFiles('iac/.terraform.lock.hcl') }}

      - name: Set vars
        id: vars
        run: |

          APP_RELEASE="dev"

          if [ "${{ github.ref }}" = 'refs/heads/master' ]; then
            APP_BRANCH="dev"
            PARAM_SPACE="dev"
          elif [ "${{ github.ref }}" = 'refs/heads/iac' ]; then
            APP_BRANCH="dev"
            PARAM_SPACE="dev"
          else
            APP_BRANCH="dev"
            PARAM_SPACE="dev"
          fi

          APP_BRANCH=${{ inputs.branch_name }}

          echo "APP_RELEASE=$APP_RELEASE"
          echo "REF_SLUG=$REF_SLUG"
          echo "APP_BRANCH=$APP_BRANCH"

          echo "app_release=$APP_RELEASE" >> $GIHTUB_ENV
          echo "ref_slug=$REF_SLUG" >> $GIHTUB_ENV
          echo "app_branch=$APP_BRANCH" >> $GIHTUB_ENV
          echo "param_space=$PARAM_SPACE" >> $GIHTUB_ENV

      - name: Terraform Init
        run: |
          echo  "tag          =\"${{env.tag}}\""  >  terraform.auto.tfvars
          echo  "app_release  =\"${{env.tag}}\""  >>  terraform.auto.tfvars
          echo  "app_branch  =\"${{env.app_branch}}\""  >>  terraform.auto.tfvars
          echo  "param_space  =\"${{env.param_space}}\""  >>  terraform.auto.tfvars
          terraform init -migrate-state
          unset TF_WORKSPACE
          terraform workspace select dev
          terraform workspace select ${{env.app_branch}} || terraform workspace new ${{env.app_branch}}
          terraform init
        working-directory: iac

      - name: Terraform Validate
        run: terraform validate
        working-directory: iac

      - name: check
        run: |
          echo "TF_VAR_tag=${{env.tag}}"
          echo "TF_VAR_app_branch=${{env.app_branch}}"
          env

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: iac

