name: Feature branch Deploy

on:
  workflow_call:
    inputs:
      repository_name:
        description: 'caller repository name'
        required: false
        type: string
      branch_name:
        description: 'name branch to deploy'
        required: true
        type: string
      tag_name:
        description: 'name tag to deploy'
        default: 'dev'
        required: false
        type: string
    secrets:
      tf_api_token:
        description: 'trerraform access token'
        required: true
      slack_webhook:
        description: 'slack webhook url'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TF_WORKSPACE: dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check branch
        id: test
        run: |
          set -x
          APP_TAG="master"

          if [ -n "$(git show-ref refs/heads/feature/${{ inputs.branch_name }})" ]; then
            echo "found feature branch $exists"
            APP_TAG="${{ inputs.branch_name }}"
          fi
          echo "APP_TAG=$APP_TAG"
          echo "::set-output name=tag::$APP_TAG"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tf_api_token }}
          terraform_wrapper: false
          terraform_version: "~1.0"

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: iac

      - name: Cache Terraform
        uses: actions/cache@v2
        with:
          path: iac/.terraform
          key: ${{ hashFiles('iac/.terraform.lock.hcl') }}

      - name: Set vars
        id: vars
        run: |

          APP_BRANCH=${{ inputs.branch_name }}
          PARAM_SPACE="dev"

          if [ APP_BRANCH = 'stage' ]; then
            PARAM_SPACE="dev"
          elif [ APP_BRANCH = 'master' ]; then
            PARAM_SPACE="dev"
          fi

          echo "::set-output name=app_branch::$APP_BRANCH"
          echo "::set-output name=param_space::$PARAM_SPACE"

      - name: Terraform Init
        run: |
          echo  "tag          =\"${{steps.test.outputs.tag}}\""  >  terraform.auto.tfvars
          echo  "app_branch  =\"${{steps.vars.outputs.app_branch}}\""  >>  terraform.auto.tfvars
          echo  "param_space  =\"${{steps.vars.outputs.param_space}}\""  >>  terraform.auto.tfvars
          terraform init -migrate-state
          unset TF_WORKSPACE
          terraform workspace select dev
          terraform workspace select ${{steps.vars.outputs.app_branch}} || terraform workspace new ${{steps.vars.outputs.app_branch}}
          terraform init
        working-directory: iac

      - name: Terraform Validate
        run: terraform validate
        working-directory: iac

      - name: Terraform Apply
        env:
          TF_WORKSPACE: ${{steps.vars.outputs.app_branch}}
          TF_VAR_app_branch: ${{steps.vars.outputs.app_branch}}
          TF_VAR_tag: ${{steps.vars.outputs.tag}}

        run: terraform apply -auto-approve
        working-directory: iac

      - name: Slack Notification
        env:
          SLACK_USER: "${{ github.repository }}[${{ steps.vars.outputs.app_branch }}]"
        run: |
          curl -fsS \
            -X POST \
            -H 'content-type: application/json' \
             "${{secrets.slack_webhook}}" \
            -d '{"channel": "#ci-cd", "username": "'"$SLACK_USER"'", "text": "Feature branch service deployed ${{ needs.vars.outputs.app_release }}\n<${{ github.server_url }}/${{ inputs.repository_name }}/actions/>", "icon_emoji": ":triangular_flag_on_post:"}'

